import type { RecoveryCase } from "@/lib/types";

export const fictionalCases: RecoveryCase[] = [
  {
    id: "case-1001",
    name: "Rahul Mehta",
    initials: "RM",
    merchant: "Learnly",
    plan: "Pro Learning Plan",
    amount: 1999,
    failureReason: "Insufficient balance",
    failedAt: "2026-10-01T09:15:00.000Z",
    status: "ready",
    risk: "medium",
    recommendedAction: "Offer a secure payment link",
    scenario: "Funds are now available and the customer is willing to pay.",
    attempts: 1,
    lastContact: null,
    phoneLabel: "Authorized demo number",
    outcome: null,
    conversationId: null,
    transcript: [],
    recoveredAt: null,
    paymentId: null,
  },
  {
    id: "case-1002",
    name: "Ananya Iyer",
    initials: "AI",
    merchant: "FitFlow",
    plan: "Annual Fitness Pass",
    amount: 3499,
    failureReason: "Expired card",
    failedAt: "2026-10-01T10:20:00.000Z",
    status: "ready",
    risk: "high",
    recommendedAction: "Send payment-method update link",
    scenario: "The saved card expired last month.",
    attempts: 2,
    lastContact: "2026-10-02T08:30:00.000Z",
    phoneLabel: "Authorized demo number",
    outcome: "SMS reminder opened; no payment",
    conversationId: null,
    transcript: [],
    recoveredAt: null,
    paymentId: null,
  },
  {
    id: "case-1003",
    name: "Kabir Shah",
    initials: "KS",
    merchant: "StreamBox",
    plan: "Family Entertainment",
    amount: 799,
    failureReason: "Temporary bank decline",
    failedAt: "2026-10-01T11:05:00.000Z",
    status: "ready",
    risk: "low",
    recommendedAction: "Explain and offer a later retry",
    scenario: "The bank reported a temporary technical failure.",
    attempts: 1,
    lastContact: null,
    phoneLabel: "Authorized demo number",
    outcome: null,
    conversationId: null,
    transcript: [],
    recoveredAt: null,
    paymentId: null,
  },
  {
    id: "case-1004",
    name: "Meera Nair",
    initials: "MN",
    merchant: "CloudDesk",
    plan: "Workspace Starter",
    amount: 1299,
    failureReason: "Insufficient balance",
    failedAt: "2026-09-30T16:40:00.000Z",
    status: "promised",
    risk: "medium",
    recommendedAction: "Follow up on promised date",
    scenario: "The customer wants to pay after salary day.",
    attempts: 2,
    lastContact: "2026-10-02T12:15:00.000Z",
    phoneLabel: "Authorized demo number",
    outcome: "Promise to pay on 5 October",
    conversationId: "demo-conversation-1004",
    transcript: [
      {
        role: "agent",
        message:
          "Would you prefer a secure payment link now or a reminder on another date?",
        timestamp: "00:24",
      },
      {
        role: "customer",
        message: "Please remind me on the fifth after my salary is credited.",
        timestamp: "00:31",
      },
    ],
    recoveredAt: null,
    paymentId: null,
  },
  {
    id: "case-1005",
    name: "Vikram Rao",
    initials: "VR",
    merchant: "NewsOne",
    plan: "Digital Premium",
    amount: 499,
    failureReason: "Customer reports already paid",
    failedAt: "2026-10-01T06:50:00.000Z",
    status: "escalated",
    risk: "high",
    recommendedAction: "Verify payment before any retry",
    scenario: "The customer believes the amount was already debited.",
    attempts: 1,
    lastContact: "2026-10-02T09:45:00.000Z",
    phoneLabel: "Authorized demo number",
    outcome: "Payment dispute sent for investigation",
    conversationId: "demo-conversation-1005",
    transcript: [],
    recoveredAt: null,
    paymentId: null,
  },
  {
    id: "case-1006",
    name: "Sana Khan",
    initials: "SK",
    merchant: "MealMint",
    plan: "Weekly Meal Plan",
    amount: 1199,
    failureReason: "Mandate paused",
    failedAt: "2026-10-01T13:35:00.000Z",
    status: "ready",
    risk: "medium",
    recommendedAction: "Explain reauthorization options",
    scenario: "The customer may want to cancel instead of reauthorizing.",
    attempts: 1,
    lastContact: null,
    phoneLabel: "Authorized demo number",
    outcome: null,
    conversationId: null,
    transcript: [],
    recoveredAt: null,
    paymentId: null,
  },
  {
    id: "case-1007",
    name: "Arjun Desai",
    initials: "AD",
    merchant: "CodeCraft",
    plan: "Developer Plus",
    amount: 2499,
    failureReason: "Bank timeout",
    failedAt: "2026-10-01T15:10:00.000Z",
    status: "ready",
    risk: "low",
    recommendedAction: "Offer callback or payment link",
    scenario: "The customer is busy and requests a callback.",
    attempts: 1,
    lastContact: null,
    phoneLabel: "Authorized demo number",
    outcome: null,
    conversationId: null,
    transcript: [],
    recoveredAt: null,
    paymentId: null,
  },
  {
    id: "case-1008",
    name: "Tara Bose",
    initials: "TB",
    merchant: "BookNest",
    plan: "Reader Unlimited",
    amount: 599,
    failureReason: "UPI mandate unavailable",
    failedAt: "2026-10-01T18:05:00.000Z",
    status: "opted_out",
    risk: "low",
    recommendedAction: "Do not call; use permitted channels only",
    scenario: "The customer asked not to receive recovery calls.",
    attempts: 2,
    lastContact: "2026-10-02T14:20:00.000Z",
    phoneLabel: "Authorized demo number",
    outcome: "Voice-call opt-out recorded",
    conversationId: "demo-conversation-1008",
    transcript: [],
    recoveredAt: null,
    paymentId: null,
  },
  {
    id: "case-1009",
    name: "Nikhil Verma",
    initials: "NV",
    merchant: "SkillSpring",
    plan: "Career Accelerator",
    amount: 4999,
    failureReason: "Card blocked",
    failedAt: "2026-09-29T07:25:00.000Z",
    status: "failed",
    risk: "high",
    recommendedAction: "Escalate after repeated no-answer calls",
    scenario: "No answer after two compliant attempts.",
    attempts: 3,
    lastContact: "2026-10-02T11:00:00.000Z",
    phoneLabel: "Authorized demo number",
    outcome: "No answer",
    conversationId: null,
    transcript: [],
    recoveredAt: null,
    paymentId: null,
  },
  {
    id: "case-1010",
    name: "Diya Patel",
    initials: "DP",
    merchant: "Mindful",
    plan: "Wellness Membership",
    amount: 899,
    failureReason: "Insufficient balance",
    failedAt: "2026-09-30T05:55:00.000Z",
    status: "recovered",
    risk: "low",
    recommendedAction: "No further action",
    scenario: "The customer used the secure link after an assisted call.",
    attempts: 2,
    lastContact: "2026-10-02T07:10:00.000Z",
    phoneLabel: "Authorized demo number",
    outcome: "Payment confirmed by webhook",
    conversationId: "demo-conversation-1010",
    transcript: [
      {
        role: "agent",
        message:
          "I have sent a secure payment link. Please complete it only on the hosted payment page.",
        timestamp: "00:38",
      },
      {
        role: "customer",
        message: "I can see the link. I will complete it now.",
        timestamp: "00:45",
      },
    ],
    recoveredAt: "2026-10-02T07:18:00.000Z",
    paymentId: "pay_demo_1010",
  },
];

export function cloneFictionalCases(): RecoveryCase[] {
  return structuredClone(fictionalCases);
}
